# Cloudflare Pages configuration
name = "atprotoblog"
compatibility_date = "2023-10-30"
main = "./build/index.js"

# Environment variables for production
[vars]
ATP_SERVICE = "https://pds.skiddle.id/"
ATP_IDENTIFIER = "skiddle.id"
ATP_DID = "did:plc:kbpcqituf5ku6xorxo2wzdee"
NODE_ENV = "production"
