# Cloudflare Pages configuration
name = "atprotoblog"
compatibility_date = "2023-10-30"

# Build configuration
[build]
command = "node cloudflare-build.js"

# Site configuration
[site]
bucket = "public/build"

# Pages specific configuration

# Environment variables for production
[vars]
ATP_SERVICE = "https://pds.skiddle.id/"
ATP_IDENTIFIER = "skiddle.id"
ATP_DID = "did:plc:kbpcqituf5ku6xorxo2wzdee"
NODE_ENV = "production"
